# Generated by Django 4.0.3 on 2022-05-25 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom_machine', models.CharField(max_length=10)),
                ('nom_utilisateur', models.CharField(max_length=15)),
                ('responsable_maj', models.CharField(max_length=15)),
                ('infrastructure', models.CharField(max_length=1)),
                ('maintenanceDate', models.DateField(default=datetime.datetime(2022, 5, 25, 12, 53, 31, 983557))),
                ('mach', models.CharField(choices=[('PC', 'PC - Run windows'), ('Mac', 'Mac - Run MacOS'), ('Serveur', 'Serveur - Simple Server to deploy virtual machines'), ('Switch', 'Switch - To maintains and connect servers')], default='PC', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Personnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('infrastructure', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('num', models.CharField(max_length=15)),
                ('date_entree', models.DateField()),
            ],
        ),
    ]
