# Generated by Django 4.0.3 on 2022-06-13 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0028_alter_infrastructure_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='nb_machine',
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 7, 59, 27, 345461)),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 7, 59, 27, 345446)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 7, 59, 27, 321646)),
        ),
        migrations.AlterField(
            model_name='personnelle',
            name='date_entree',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 7, 59, 27, 345106)),
        ),
    ]
